# Generated by Django 5.2.16 on 2026-08-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyemi',
            name='paid_emis',
            field=models.IntegerField(default=0, help_text='Number of EMIs paid so far'),
        ),
        migrations.AddField(
            model_name='monthlyemi',
            name='total_emis',
            field=models.IntegerField(blank=True, help_text='Total number of tenure EMIs', null=True),
        ),
        migrations.AddField(
            model_name='monthlyemi',
            name='total_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total loan amount', max_digits=12, null=True),
        ),
    ]
