# Generated by Django 6.0.3 on 2026-07-21 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_card_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Account Balances',
            },
        ),
        migrations.CreateModel(
            name='MonthlyEMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_day', models.IntegerField(help_text='Day of month (1-31)')),
                ('full_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personal_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split_with', models.CharField(blank=True, help_text='Comma-separated names', max_length=200)),
                ('category', models.CharField(choices=[('emi', 'EMI'), ('subscription', 'Subscription'), ('insurance', 'Insurance'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('other', 'Other')], default='emi', max_length=20)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=10)),
                ('month_year', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Monthly EMIs',
                'ordering': ['due_day'],
            },
        ),
        migrations.CreateModel(
            name='SplitDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('debt_type', models.CharField(choices=[('debt', 'I Owe (Debt)'), ('credit', 'They Owe Me (Credit)')], max_length=6)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('settled', 'Settled')], default='pending', max_length=7)),
                ('reason', models.TextField(blank=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Split Debts',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('emi', 'EMI Payment'), ('debt_payment', 'Debt Payment'), ('credit_received', 'Credit Received'), ('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaction History',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
