# Generated by Django 5.2 on 2026-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_monthlyemi_paid_emis_monthlyemi_total_emis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitdebt',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number of beneficiary / contact', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='splitdebt',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID / Bank details (Optional)', max_length=50, null=True),
        ),
    ]
