# Generated by Django 5.2 on 2026-08-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_beneficiary_splitdebt_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='cash_in_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
