# Generated by Django 5.2 on 2026-08-04 07:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_accountbalance_cash_in_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='is_split',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='payment_mode',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('cash', 'Cash in Hand'), ('credit_card', 'Credit Card')], default='bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='TransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split_type', models.CharField(choices=[('credit', 'They Owe Me (Credit)'), ('debt', 'I Owe Them (Debt)')], default='credit', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.beneficiary')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='finance.transactionhistory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
