# Generated by Django 5.0.6 on 2026-08-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_transactionhistory_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
